source: forty-jekyll-theme/
paths:
  uploads: uploads
  dam_uploads: ''
  static: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  posts:
    path: _posts
    output: true
    icon: notes
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: 
    output: true
    filter: strict
    description: ''
    icon: notes
    _editables: {}
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
_enabled_editors:
  - content
  - data
  - visual
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_select_data:
  socials:
    GitHub: https://github.com/andrewbanchich
    GitLab:
    Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
    Instagram:
    LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
    Twitter: https://twitter.com/andrewbanchich
    Facebook:
    Slack:
  sass:
    style: compressed
_structures: {}
_editables: {}
base_url: forty-jekyll-theme
data_config: {}
editor:
  default_path:
timezone: Asia/Kolkata
